# Generated by Django 5.2.15 on 2026-06-17 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=80)),
                ('monthly_token_allowance', models.PositiveIntegerField(default=100)),
                ('tokens_sent_this_month', models.PositiveIntegerField(default=0)),
                ('last_reset_month', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('ownership', 'Ownership'), ('teamwork', 'Teamwork'), ('innovation', 'Innovation'), ('customer', 'Customer Impact'), ('safety', 'Safety')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recognitions', to='recognition.employeeprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_recognitions', to='recognition.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
