# Generated by Django 5.2.15 on 2026-06-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('staff', 'Staff'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
